const Anthropic = require("@anthropic-ai/sdk");

const client = new Anthropic();
const TARGET_STACK = [
    "react", "angular.js", "angularjs",
    "node", "node.js", "nodejs",
    "express", "express.js", "expressjs",
    "typescript", "javascript",
    "next.js", "nextjs",
    "tailwind", "tailwindcss", "tailwind css"
];
const MIN_EMPLOYEES = 5;
const MAX_EMPLOYEES = 200;
const MIN_DESCRIPTION_LENGTH = 50;
const MAX_DESCRIPTION_LENGTH = 500;
const MAX_TOKENS = 1024;

function getTextWindows(text, keywords, windowSize = MIN_DESCRIPTION_LENGTH) {
    let windows = [];

    for (kw of keywords) {
        const kwIdx = text.indexOf(kw);
        if (kwIdx !== -1) {
            const halfWindowSize = Math.round(windowSize / 2);
            if (kwIdx > halfWindowSize) {
                windows.push(text.slice(kwIdx - halfWindowSize, kwIdx + halfWindowSize));
            } else {
                windows.push(text.slice(0, windowSize));
            }
        }
    }

    return windows;
}

function preFilter(extractedText) {
    return getTextWindows(extractedText, TARGET_STACK).flat().toString();
}

async function extractStructured(job) {
    if (!job.extractedText) return { ...job, tech_stack: [], employee_count: null };

    const extractedText = preFilter(job.extractedText);
    if (extractedText.length < MIN_DESCRIPTION_LENGTH) return { ...job, tech_stack: [], employee_count: null };
    if (extractedText.length > MAX_DESCRIPTION_LENGTH) extractedText = extractedText.slice(0, MAX_DESCRIPTION_LENGTH);


    const message = await client.messages.create({
        model: "claude-haiku-4-5-20251001",
        max_tokens: MAX_TOKENS,
        // web_search_20260209 is a server-side tool — Claude searches internally and
        // returns a final text response; no client-side tool loop needed.
        tools: [{ type: "web_search_20260209", name: "web_search", allowed_callers: ["direct"] }],
        messages: [{
            role: "user",
            content: `1. Search the web lightly and approximate the headcount of "${job.company}".
2. Extract the tech stack from the job posting.

Return only valid JSON with no explanation:
{
  "tech_stack": ["array of technologies, languages, and frameworks mentioned"],
  "employee_count": <number if found via web search, otherwise null>
}

Job posting:
${extractedText}`
        }]
    });

    try {
        // Grab the last text block — web_search may produce intermediate content blocks
        // before the final JSON response.
        const textBlock = message.content.filter(b => b.type === 'text').pop();
        if (!textBlock) return { ...job, tech_stack: [], employee_count: null };

        const raw = textBlock.text.replace(/^```(?:json)?\n?|\n?```$/g, '').trim(); // remove markdown code fences generated by Claude
        const parsed = JSON.parse(raw);
        return {
            ...job,
            tech_stack: parsed.tech_stack ?? [],
            employee_count: parsed.employee_count ?? null
        };
    } catch {
        return { ...job, tech_stack: [], employee_count: null };
    }
}

function hardFilter(jobs) {
    return jobs.filter(job => {
        const stack = job.tech_stack.map(s => s.toLowerCase());
        const hasStackMatch = TARGET_STACK.some(skill => stack.some(s => s.includes(skill)));
        const withinSize = job.employee_count === null || (job.employee_count >= MIN_EMPLOYEES && job.employee_count <= MAX_EMPLOYEES);
        return hasStackMatch && withinSize;
    });
}

async function filter(jobs, limit) {
    // Process in batches to avoid Anthropic rate limiting — if all 100+ jobs are fired
    const BATCH_SIZE = 5;
    const extracted = [];
    const maxJobs = jobs.length < limit ? jobs.length : limit;
    for (let i = 0; i < maxJobs; i += BATCH_SIZE) {
        const batch = await Promise.all(jobs.slice(i, i + BATCH_SIZE).map(extractStructured));
        extracted.push(...batch);
    }
    return hardFilter(extracted);
}

module.exports = { filter };
